### ISSUE TITLE
Invalid value for PATHS

### ISSUE THREAD

**Issue by mrswats** [simonw/markdown-to-sqlite#7]
I am trying to generate a database to run inside docker. However, while in my terminal this works fine
```bash
$ markdown-to-sqlite blog.db posts "./_blog/**/*.md"
```
when it runs inside the docker I get the following error:
```
Error: Invalid value for 'PATHS...': Path './_blog/**/*.md' does not exist.
Error: error building at STEP "RUN markdown-to-sqlite blog.db posts "./_blog/**/*.md"": error while running runtime: exit status 2
```

And I am not quite sure why it does not. I guess it has to do with the shell it runs on (on my machine I am running zsh while the docker one is just sh) but I do not know how work around it.

Any and all help will be much appreciated!

**Comment by simonw** [comment]
Try doing this without those double quotes - they are likely preventing the * from being correctly evaluated.

**Comment by mrswats** [comment]
Okay, I figured it out, it was not the quotes.

While zsh was capable of interpreting the `**` as any number of directories within `_blog/`, for some reason inside the container it was not able to expand recursively and so I had to use `_blog/**/**/*,md` instead (as there are two levels of folders in there representing year and month).
